### ISSUE TITLE
How can I get the path for recorded file?

### ISSUE THREAD

**Issue by mishu311289** [HBiSoft/HBRecorder#105]
I tried but I'm only getting content uri which is not getting converted to a valid file path. Getting file not found exception while trying to compress the video file. Any help will be much appreciated.

**Comment by HBiSoft** [comment]
`hbrecorder.getFilePath()` will only return the file path if it was set using `hbrecorder.setOutputPath(String)`. This library doesn't convert `Uri`'s to File paths, it returns the file path that was set, if it was set. You can have a look at the demo application:

https://github.com/HBiSoft/HBRecorder/blob/d8efaae89566ca221827a255106589737cfca36b/app/src/main/java/com/hbisoft/hbrecorderexample/MainActivity.java#L606-L631

**Comment by mishu311289** [comment]
yeah I got that but my requirement is to compress the recorded file once recording is complete so I need to get information about where did the recorded file saved. When I'm trying to convert the output uri (which I'm setting via setOutputUri) to file path it's resulting in file not found exception so I just want to ask how can I get the information on path where the recorded file was saved so that I can pick the file and compress it.
