### ISSUE TITLE
Screen record for specific Application

### ISSUE THREAD

**Issue by MohsenAbdelkareem** [HBiSoft/HBRecorder#11]
Could we record only specific running application screen?

**Comment by HBiSoft** [comment]
If it is your application, then yes.

You can stop the recording by checking if the user leaves the `Activity`, in `onPause()`, like this:

```java
@Override
public void onPause(){
    hbRecorder.stopScreenRecording();
    super.onPause();
}
```

There is no way of limiting the recording to a specific application, accept your own.
