### ISSUE TITLE
Notification Timer to know how much time has passed since starting recording

### ISSUE THREAD

**Issue by blazingdevil44** [HBiSoft/HBRecorder#116]
Hi Can you please tell me how to add timer to notification so you can length of video in Realtime ill be really grateful for your answer thanks in advance

**Comment by HBiSoft** [comment]
I might look at implementing this, but I do not have the time at the moment. I will try and look at it over the weekend.

**Comment by blazingdevil44** [comment]
I did it by adding .setUsesChronometer(true) in notification its simple and easy i dont know if it works on older api but its working for me xD
