### ISSUE TITLE
setAudioSource failed

### ISSUE THREAD

**Issue by thanhbouet** [HBiSoft/HBRecorder#118]
I am using HBRecorder, i had error " *[java.lang.RuntimeException: setAudioSource failed] many times but i don't know where it come from.  I had cheked AUDIO_RECORD permission and it's ok. Can you tell me where this error come from. Thanks and sorry for my bad English.

**Comment by HBiSoft** [comment]
Please run the demo application and provide me with the log after opening the application.

Also, please let me know what you set as your audio source?

**Comment by HBiSoft** [comment]
I will reopen this issue once I get a response.
