### ISSUE TITLE
Can I hide the permission pop up which display before starting the recording 

### ISSUE THREAD

**Issue by pranitshirsath** [HBiSoft/HBRecorder#120]
The pop up which displays first before starting the recording which says this app will capture all the things display on your screen and when we click on start button then it's start recording. 

so can we skip that part and directly start the recording, can anyone please provide me any solution on it.

**Comment by HBiSoft** [comment]
No you can not. Screen recording must be done in a foreground service and to start a foreground service this notification gets shown by the operating system. There is no way of hiding this.

On older devices you can say, "don't show this again". But since Android 10, this is not possible.
