### ISSUE TITLE
Enable Audio Recording while video is in Progress

### ISSUE THREAD

**Issue by hemandroid** [HBiSoft/HBRecorder#122]
Hi Team,

I tried using the plugin and when I enable the audio as default before video record starts. It's working perfectly, but before video recording starts, I disable the Audio and enabled it after starting the video recording. This time, video is not recording the audio.

I tried like below

```
private void setRecordAudioCheckBoxListener() {
        recordAudioCheckBox.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
            @Override
            public void onCheckedChanged(CompoundButton compoundButton, boolean isChecked) {
                //Enable/Disable audio
                isAudioEnabled = isChecked;
                hbRecorder.isAudioEnabled(isChecked);
            }
        });
    }
```
Please suggest how to handle the audio recording along with Screen recording dynamically.

**Comment by HBiSoft** [comment]
It's not currently possible, but shouldn't be hard to implement.

`hbRecorder.isAudioEnabled(isChecked)` is meant to be set before starting the recording.

I will have a look at it later today. I will let you know when I'm done adding it to the library.
