### ISSUE TITLE
Screen Recording Pause, Resume and Stop Feature on Notification Panel.

### ISSUE THREAD

**Issue by hemandroid** [HBiSoft/HBRecorder#123]
Can we get the feature to pause, resume & stop the screen recording from the Notification Panel.

At the moment, even when we pause the screen recording, it was showing only Stop recording Button. Instead of Resume & Stop Recording options. Notification panel is not having that flexibility at the moment.

@HBiSoft Need support on these feature requests.

**Comment by HBiSoft** [comment]
I will see if I can implement it in the next release.
