### ISSUE TITLE
Demo app not working on Android 12

### ISSUE THREAD

**Issue by DiegoJRAleixandre** [HBiSoft/HBRecorder#124]
**Describe the bug**
Demo app not working on Android 12

**Log**
When downloading the .apk I cannot install it. When using abd to try and install it I get the following error:

adb: failed to install HBRecorderDemo.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl274285536.tmp/base.apk (at Binary XML file line #27): com.hbisoft.hbrecorderexample.MainActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]

Doing a quick search as I know not much about android development I see that people suggest to write the following in the AndroidManifest.xml:

<activity
     android:exported="true"
 < /activity >

**HBRecorder version**
for example 2.0.5

**Device information**
- Samsung Galaxy lite S6

**Comment by HBiSoft** [comment]
Thanks for letting me know. I will fix this in the next update.
