### ISSUE TITLE
Freezes /lags onstart hbrecorder

### ISSUE THREAD

**Issue by damylolae** [HBiSoft/HBRecorder#125]
**Describe the bug**
Didn't crash , but totally frooze UI, suspecting a memory leak, not sure because I tested it on a 1gb ram, 16gb (itel p33+)storage no issues at all, but another device having exactly same memory and CPU it lags (itel5001p).

**Log**
Nil

**Can it be reproduced in demo app**
Really don't know , users complaint

**HBRecorder version**
2.0.5

**Device information**
- itel5001p, tech no wx3p
- Android 8.1, Android 7.1

**Screenshots**

**Comment by HBiSoft** [comment]
Apologies for the late reply. Can you please try the previous release - https://github.com/HBiSoft/HBRecorder/releases/tag/2.0.4
