### ISSUE TITLE
mediaProjectionManager.createScreenCaptureIntent() return null

### ISSUE THREAD

**Issue by Zigo-Stephano** [HBiSoft/HBRecorder#133]
I use kotlin for this app dependency and when i create intent for mediaProjectionManager.createScreenCaptureIntent() then startActivityForResult, the data: Intent? return null
Can you help me with that pls ??
<img width="920" alt="Screenshot 2022-12-02 at 19 52 33" src="https://user-images.githubusercontent.com/93713501/205297242-d4507339-28ed-403c-bc86-3cc699aa36bb.png">

**Comment by HBiSoft** [comment]
Please provide me with the entire activity for me to test it on my side.

**Comment by Zigo-Stephano** [comment]
[ScreenRecordExample.zip](https://github.com/HBiSoft/HBRecorder/files/10144903/ScreenRecordExample.zip)
This is the full project
