### ISSUE TITLE
Can I get audio file that recorded from screen recording?

### ISSUE THREAD

**Issue by aeiou-st** [HBiSoft/HBRecorder#136]
Hello,
So question is i want audio file that recorded from HB recorder. I look into all resources that provided by HB recorder but i didn't get my answer.
If there is any solution for it like how can i store audio file in different folder.

>If I ask you why screen recording file have size like 10 MB for 10 seconds. You should implement compression feature in it.

**Comment by aeiou-st** [comment]
As i know this feature available in 1.2.3 as setAudioPath() method but now I didn't find it.

**Comment by HBiSoft** [comment]
@aeiou-st 
As the library stands now, it's not possible. I will possibly look into adding this at a later stage. You are however more than welcome to implement this and create a pull request.
