### ISSUE TITLE
FileObserver - The observer watch the whole parent directory

### ISSUE THREAD

**Issue by revkusz** [HBiSoft/HBRecorder#138]
In the FileObserver class the path passed is the parent directory of the output path. So while i recording i cannot close a file in that directory bc if i close a file the recorder thinks the file was closed by the recorder, the fileobserver never checks if the file that was closed was the recorded file or not. Is there a reason for this or this is a bug?

**Comment by revkusz** [comment]
No comment on this?

**Comment by HBiSoft** [comment]
I'm not sure what you mean with
> i cannot close a file in that directory

Can you please provide me with an example for clarification?

**Comment by bomberaya** [comment]
This is a real issue.
Because of this, the `HBRecorderOnComplete()` callback will get invoked whenever a file is written to the target directory of the HBRecorder.

Here is a mini-example (put this in `onActivityResult()` of your `Activity`):
```
public fun test(activity: Activity, result: ActivityResult) {
    if (result.resultCode != Activity.RESULT_OK) return
    // Set up HBRecorder and listener
    val hbRecorder = HBRecorder(activity, object : HBRecorderListener {
        override fun HBRecorderOnComplete() {
            Log.d("HBRecorder", "HBRecorderOnComplete")
        }
        override fun HBRecorderOnStart() {
            Log.d("HBRecorder", "HBRecorderOnStart")
        }
        override fun HBRecorderOnError(errorCode: Int, reason: String?) {
            Log.d("HBRecorder", "HBRecorderOnError")
        }
        override fun HBRecorderOnPause() {
            Log.d("HBRecorder", "HBRecorderOnPause")
        }
        override fun HBRecorderOnResume() {
            Log.d("HBRecorder", "HBRecorderOnResume")
        }
    })
    // Set destination directory
    val destinationDir = activity.getExternalFilesDir(Environment.DIRECTORY_MOVIES)
    hbRecorder.setOutputPath(destinationDir!!.absolutePath)
    hbRecorder.fileName = "screen_recording.mp4"
    // Start recording
    hbRecorder.startScreenRecording(result.data, result.resultCode)
    CoroutineScope(Dispatchers.Main).launch {
        delay(3000) // Delay for 3 seconds
        FileUtils.saveTextAsFile("Random text", destinationDir, "test.txt") // Create a different file in the same directory
        // ...
        // Notice `HBRecorderOnComplete` being invoked (in logcat)
    }
}
```

I can create a PR with the fix when I have some free time.

**Comment by HBiSoft** [comment]
@bomberaya That makes sense. Thanks for clarifying. 

This should be easily fixed by checking in FileObserver - OnEvent if the name of the file matches the one we are creating.

I'm not currently at a computer, but I will see if I can implement/fix this tomorrow.
