### ISSUE TITLE
Screen record permission request

### ISSUE THREAD

**Issue by BorisSomoff** [HBiSoft/HBRecorder#143]
At now,  Screen record permission requested every time at record start
As I know, it is  no problem to make this request only first time of start record in current session.
Is it  possible to implement this feature in settings?

**Comment by HBiSoft** [comment]
My apologies for the late reply. No there is no way of forcing permissions to be only asked once. Because it's a foreground service, Android itself asks for this permission and we have no control over this.

**Comment by jdevp** [comment]
But it should have options to check if Foreground and permission intent is running. If they are , don't start new ones. Then you can do is keep them running all the times, only stop media recorder and virtual display when you are done with recording and start new ones when with new recording.
