### ISSUE TITLE
Use for new versions

### ISSUE THREAD

**Issue by MrNouri** [HBiSoft/HBRecorder#144]
Hi, thanks for this great library. ❤️
I want create new application with Kotlin and I want support android 14. 
Can I use this library for all of devices? such as Samsung, Xiaomi, Huawei and more... with different of CPU and GPU 
Thanks🙏

**Comment by HBiSoft** [comment]
I have not tested it on Android 14, but there is no reason why it shouldn't work. I'm only using Android APIs in this library, so yes it will work on all Android devices regardless of the make.
