### ISSUE TITLE
File  format is not supported or Files are corrupted

### ISSUE THREAD

**Issue by tanayjoshi21** [HBiSoft/HBRecorder#145]
READ THIS BEFORE OPENING AN ISSUE:
-----------------------
- Fill in all the information below.
- Have a look at previously asked questions to see if your issue has been resolved.
- Properly format your issue.
- All issues should be asked in English.
- Delete all the above before posting your issue

**Describe the bug**
After completing the recording sometimes file is not opening and in gallery it is showing "File  format is not supported or Files are corrupted"

**Log**
Nothing in the logs 

**Can it be reproduced in demo app**
Yes 

**HBRecorder version**
3.0.1

**Device information**
- Redmi Note 8 , Samsung M13 

**Screenshots**

![WhatsApp Image 2023-06-15 at 10 37 29 PM](https://github.com/HBiSoft/HBRecorder/assets/98829900/bdede488-d25b-458a-8c59-237eaed580d3)

**Comment by HBiSoft** [comment]
Sorry for the late reply. This is most probably caused by using an encoder that's not supported by your device. In the demo app, try selecting `H264` in the custom settings.
