### ISSUE TITLE
Add Initial Count Down, Orientation mode, and Floating action pop-up options.

### ISSUE THREAD

**Issue by brittle123** [HBiSoft/HBRecorder#15]

**Comment by HBiSoft** [comment]
I will be closing this issue.

Please create a new issue by pressing "New issue" then select "Future request":
![Screenshot 2020-06-15 at 09 46 28](https://user-images.githubusercontent.com/35602540/84631296-6d275d80-aeed-11ea-992d-8bfeabfbb4bf.png)

Then fill in all the fields. Give as much as possible information and provide a proper title, for example - "Requesting features".

This is not how you open issues on Github.
