### ISSUE TITLE
Upgrade to SDK 34

### ISSUE THREAD

**Issue by MrNouri** [HBiSoft/HBRecorder#153]
Thanks for this great library <3 
I want use this library for target **SDK 34** but after start recording show ForceClose error. <br>
show `register mediaprojection` error for this line
```
    private void initVirtualDisplay() {
        mVirtualDisplay = mMediaProjection.createVirtualDisplay(TAG, mScreenWidth, mScreenHeight, mScreenDensity, DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR, mMediaRecorder.getSurface(), null, null);
    }
```

Can you fix it?

**Comment by HBiSoft** [comment]
I will update the library today to support SDK 34.
