### ISSUE TITLE
Library not visible in project

### ISSUE THREAD

**Issue by mbermeleev** [HBiSoft/HBRecorder#158]
I`ve updated to new version(3.0.2) of library, but in project not visible imports. What am I doing wrong?
I only have updated number of version in my build.graddle

**Comment by faran432** [comment]
I am also facing this issue. I have added the library in Android project, and its not adding library to project. I have checked External libraries list as well. 

But gradle syncs successfully.

**Comment by Abhi-sirohi** [comment]
same issue here

**Comment by faran432** [comment]
I downgraded library version to 2.x.x and continued my work

**Comment by Abhi-sirohi** [comment]
> I downgraded library version to 2.x.x and continued my work

but that does not solve the SDK 34 issue!

**Comment by faran432** [comment]
Nice. I will check my targetSdk then. It shouldn't be less then 34

**Comment by arunk167** [comment]
having same issue

**Comment by alihamzaazhar** [comment]
Any solution?

**Comment by HBiSoft** [comment]
I tested and this is fixed in `3.0.3`

**Comment by robrechtme** [comment]
Can confirm it is fixed. Thanks for following this up so quickly! 🙏
