### ISSUE TITLE
Video save in encrypted format even save recording

### ISSUE THREAD

**Issue by furqanzaidi** [HBiSoft/HBRecorder#162]
Video save in encrypted form even i use all encoders like default and H264

When initiating a recording, a file is successfully created in the designated folder. However, upon stopping or saving the recording, the application continues to display the initially created file. Interestingly, clearing the app data resolves this issue, making the recording viewable. This suggests that the problem lies within the recording service rather than the encoder, as previously suggested. Manually stopping the service by clearing the app data enables the recording to be saved correctly. Please refer to the provided [video link](https://imgur.com/a/lbhBTJO) for further clarification. Thank you for your attention to this matter.

**Comment by mostofar45** [comment]
soy nuevo , encontré esta manera de contactarme al grabar , me he fijado que tengo un límite de 12 videos , que se guardan ¿Está bien eso? Los demás vídeos que se graban después , ya no aparecen ... Creo se guarda en DATOS DE USURIO en el móvil , Xiaomi. ¿Como hago para ver el contenido de Datos de Usuario? Son 5gb.:/

**Comment by HBiSoft** [comment]
My apologies for the delayed response. You have probably moved on from this already.
If not, can you please try the latest version 3.0.5, and get back to me?

Closing for now.
