### ISSUE TITLE
Recording Error 

### ISSUE THREAD

**Issue by MuhammadDanyalRehmanOfficial** [HBiSoft/HBRecorder#163]
D/MediaRecorder(17481): constructor E 0xb0ffc4c0
D/MediaRecorder(17481): constructor X 0xb0ffc4c0
D/MediaRecorder(17481): init E 0xb0ffc4c0
D/MediaRecorder(17481): init X 0xb0ffc4c0
D/MediaRecorder(17481): prepare E 0xb0ffc4c0
D/MediaRecorder(17481): prepare X 0xb0ffc4c0
W/H2BGraphicBufferProducer(17481): getConsumerUsage is not fully supported
D/MediaRecorder(17481): start E 0xb0ffc4c0
D/MediaRecorder(17481): start X 0xb0ffc4c0
E/Video Start:(17481): Start called
I/flutter (17481):       >>> Start Record Response Output:  
I/flutter (17481):       File: File: '-2024-04-13-06-59-22.mp4' 
I/flutter (17481):       Event Name: startRecordScreen  
I/flutter (17481):       Progressing: true 
I/flutter (17481):       Message: Started Video 
I/flutter (17481):       Success: true 
I/flutter (17481):       Video Hash: 6e802cd0f93911ee815a6fa356cfa296 
I/flutter (17481):       Start Date: 1712973555745119 
I/flutter (17481):       End Date: null
I/flutter (17481):       
I/flutter (17481): Start 
E/Video Error:(17481): 100
D/MediaRecorder(17481): reset E 0xb0ffc4c0
D/MediaRecorder(17481): doReset E 0xb0ffc4c0
D/MediaRecorder(17481): doReset X 0xb0ffc4c0
D/MediaRecorder(17481): close E 0xb0ffc4c0
D/MediaRecorder(17481): close X 0xb0ffc4c0
D/MediaRecorder(17481): reset X 0xb0ffc4c0
E/Video Error:(17481): 268435556

**Comment by HBiSoft** [comment]
You have probably moved on from this issue by now. I have just released 3.0.4. If you want, you can test to see if the issue persists. If it does, please provide me more details on how I can reproduce it. Thanks. Closing for now.
