### ISSUE TITLE
The recorded video has no sound with targetSdk is 34

### ISSUE THREAD

**Issue by WildSaber** [HBiSoft/HBRecorder#171]
**Describe the bug**
We have reproduced the issue in the demo app. When you click the "Start" button to record a video and then close the app, the recorded video has no sound.
This problem only occurs when the targetSdk is set to 34. It does not occur with lower targetSdk versions, such as 33.

**Log**
The log is not required for this issue.

**Can it be reproduced in demo app**
Yes.

**HBRecorder version**
3.0.3

**Device information**
- Model: Samsung S22 Ultra (SM-S908E)
- Android version: 14 (API level 34)

**Screenshots**
Screenshots are not required for this issue.

**Comment by HBiSoft** [comment]
Please try the new release 3.0.4

I'm using a Samsung S22 Ultra and the sound gets recorded.

Closing for now. Let me know after you have tested.
