### ISSUE TITLE
Error on audio recording in background

### ISSUE THREAD

**Issue by jfmargar** [HBiSoft/HBRecorder#172]
This problem appear on demo app. When the app go to background the audio recording stops. Video recording works fine but without audio. When de app back to foreground audio recording works fine

I've test on multiple devices and recent android versions.

**Comment by jfmargar** [comment]
I think the problem is RECORD_AUDIO permission. On android 13 this permission can't be rejected on background. How this could be solved

**Comment by HBiSoft** [comment]
Please test with 3.0.4 I just released. If the issue still persists, please provide more info on how I can reproduce it, what device you are using and what settings you are using.

**Comment by jfmargar** [comment]
Thanks, I've resolved the issue by this way:

ScreenRecordService.java Line 576:
            startForeground(notificationId, notificaton, ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION | ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE);

And on AndroidManifest:
            android:foregroundServiceType="mediaProjection|microphone"

This solve the problem. I think that the reason is new android microphone permission restrictions

**Comment by HBiSoft** [comment]
You are correct, thanks. I have updated the library again. The changes are available in 3.0.5

**Comment by Ljubisastankovic** [comment]
@HBiSoft It looks like this fix imposed that audio permission must be granted even when audio is not being used while recording. This results in unnecessary audio permission request. 

Maybe it would be more reasonable to apply `ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE` only if audio is enabled in `HbRecorder`.

**Comment by HBiSoft** [comment]
@Ljubisastankovic 
I see what you are saying.

I will test it on my side and implement it ASAP.

**Comment by Ljubisastankovic** [comment]
Many thanks! We were applying a workaround, but if you are planing to release a patch soon we might be able to postpone it.

**Comment by HBiSoft** [comment]
@Ljubisastankovic 
I'm currently busy with it. I will let you know within the next 30 minutes.

**Comment by HBiSoft** [comment]
@Ljubisastankovic 
Fixed it [3.0.8](https://github.com/HBiSoft/HBRecorder/releases/tag/3.0.8)

Thanks for letting me know about this👍

**Comment by Ljubisastankovic** [comment]
Confirmed, works as expected, big kudos for prompt action!  💯
