### ISSUE TITLE
Can we add an overlay while screen is recording?

### ISSUE THREAD

**Issue by informsharique** [HBiSoft/HBRecorder#178]
**Is your feature request related to a problem? Please describe.**
No.

Can we show on floating action overlay when the screen is recording and that provides a few options like going back to the application and stopping the recording? Not sure on the stock but several Android skins do provide this option.

**Comment by HBiSoft** [comment]
Yes, you can.

This is not available in the library, but you can implement it yourself.
When I have time available, I will implement it in the demo application.
