### ISSUE TITLE
Project Build with android 28

### ISSUE THREAD

**Issue by adnanmacro** [HBiSoft/HBRecorder#18]
Hi,
I am getting error while building app with android 28? Can you please assist.
Let me elaborate.

I Set the TargetSDK and CompileSDK to version 28
I clean the Project
Run the Rebuild

getting below errors 

\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:16: AAPT: error: attribute android:requestLegacyExternalStorage not found.

app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:34: AAPT: error: attribute android:foregroundServiceType not found.

let me know if still need to provide more details.

**Comment by HBiSoft** [comment]
What error? Please edit your question and provide more information, including device, steps to reproduce and the log.

**Comment by HBiSoft** [comment]
The library is build with SDK version 29 and uses packages released in SDK 29, like `requestLegacyExternalStorage` and `foregroundServiceType`.

Please use SDK version 29>.

**Comment by adnanmacro** [comment]
Thanks.
Do you have with version 28?

**Comment by HBiSoft** [comment]
It's expected from developers that libraries target the latest version. Just change your target version to 29, it's anyway recommended by Google to target the latest version.
