### ISSUE TITLE
SecurityException: Media projections require a foreground service of type FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION, Android 15 Foreground Service Issue.

### ISSUE THREAD

**Issue by rajatboy** [HBiSoft/HBRecorder#182]
Issue in **Android 14 or 15**:
-----------------------
- SecurityException.
- Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
- while permission FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION is added in maniefest.

**Describe the bug**
When implementing screen recording using a MediaProjection and associating it with a foreground service in Android, the recording functionality might stop working after specifying the FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION in the service declaration. This issue typically arises due to misconfiguration or incorrect usage of the foreground service in combination with the MediaProjection API.

**Log**
Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOR
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
	at android.media.projection.MediaProjection.<init>(MediaProjection.java:59)
	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:119)

**HBRecorder version**
3.0.7

**Device information**
- Make/model: Emulator or Samsung Galaxy s24 Ultra
- SDK version: 35

**Comment by HBiSoft** [comment]
Please test the [demo application](https://github.com/HBiSoft/HBRecorder/releases/download/3.0.7/HBRecorderDemo.apk).

___

Runtime permissions in the demo app are handled here:

https://github.com/HBiSoft/HBRecorder/blob/29abff85521dcc97fc03578126964931beb07cff/app/src/main/java/com/hbisoft/hbrecorderexample/MainActivity.java#L200-L240

**Comment by dixit-gabani** [comment]
If app does not require microphone usage and you are targeting Android 14 or higher, then how to start service...
in dependency start foreground service is like...
```
    private void startFgs(int notificationId, Notification notificaton) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE){
            startForeground(notificationId, notificaton, ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION | ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE);
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            startForeground(notificationId, notificaton, ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION);
        } else {
            startForeground(notificationId, notificaton);
        }
    }
```
    
how to **start foreground service without** ServiceInfo.**FOREGROUND_SERVICE_TYPE_MICROPHONE** ?

**Comment by rajatboy** [comment]
### Thank you for bringing this to my attention. After investigating the issue, I discovered that the problem is related to the following permission:

For Android 14 and above how to start foreground service without **_android.permission.FOREGROUND_SERVICE_MICROPHONE_** ?

Here is the library code to [start foreground service](https://github.com/HBiSoft/HBRecorder/blob/master/hbrecorder/src/main/java/com/hbisoft/hbrecorder/ScreenRecordService.java#L617).
```
private void startFgs(int notificationId, Notification notificaton) {
  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE){
    startForeground(notificationId, notificaton, ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION | ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE);
  } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
    startForeground(notificationId, notificaton, ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION);
  } else {
    startForeground(notificationId, notificaton);
  }
}
```

<uses-permission android:name="**_android.permission.FOREGROUND_SERVICE_MICROPHONE_**" \/>

This permission is not declared in my app's manifest because my app does not require it. However, upon reviewing the library code, I noticed that a foreground service is being started with this ServiceInfo flag (**_ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE_**), which is likely causing the conflict.

i think there should be one option to start recording without **FOREGROUND_SERVICE_TYPE_MICROPHONE** in dependency.

Please let me know if there’s anything further you'd recommend or any additional details needed.

**Comment by HBiSoft** [comment]
@rajatboy 
That's what I thought the issue was.

The demo app is only to demonstrating how the library works, how you implement it into your app is up to you.

I'm glad you found the issue.

I will be closing the issue.
