### ISSUE TITLE
[Feature-request] Dont ask for Mic permissions if I choose a no-audio screen record.

### ISSUE THREAD

**Issue by Palloxin** [HBiSoft/HBRecorder#183]
## Description
The app ask microphone permissions even if the recording is set to not pick audio.

I would like to just use the no-audio without giving mic permissions

**Comment by HBiSoft** [comment]
Both of the issues you opened are related to the demo app and not the library. The demo app is to show how to use the library and not to be used as is.

**Comment by HBiSoft** [comment]
This is fixed in [3.0.8](https://github.com/HBiSoft/HBRecorder/releases/tag/3.0.8)

**Comment by Palloxin** [comment]
3.0.9

https://github.com/user-attachments/assets/8f8ba534-861f-4734-99aa-acaa5f8eb04f

It's still there unfortunately.
(i checkmarked "don't ask again" on the permission popup window, it's not a bug)

**Comment by HBiSoft** [comment]
Uninstall the app and install the one I published today: [3.0.9](https://github.com/HBiSoft/HBRecorder/releases/tag/3.0.9)

**Comment by Palloxin** [comment]
Same behaviour. Still ask for mic perms even when i dont need it.

**Comment by HBiSoft** [comment]
I see where the problem is. I can't believe it's taking me 3 releases to fix a simple issue like this lol

I will update the library now
