### ISSUE TITLE
[Bug] Start button changes to Stop despite recording on having started

### ISSUE THREAD

**Issue by Palloxin** [HBiSoft/HBRecorder#184]
**Describe the bug**
Open app, click Start button, an android confirmation window of screen capturing appears, yet the button already changed to "Stop".

**Log**
Please provide a well formatted bug report (by adding 4 spaces before the log)

**Can it be reproduced in demo app**

**HBRecorder version**
3.0.7

**Device information**
- Make/model: huawei p8 lite 2017
- SDK version: android 8, miui 8

**Screenshots**
https://github.com/user-attachments/assets/ef44d244-492b-4446-ad8e-a4d3f1bad1f2

**Comment by HBiSoft** [comment]
Fixed in [3.0.9](https://github.com/HBiSoft/HBRecorder/releases/tag/3.0.9)
