### ISSUE TITLE
[Feature request] Add shortcut to start record to android Quick Settings panel

### ISSUE THREAD

**Issue by Palloxin** [HBiSoft/HBRecorder#185]
## Description
A simple way to trigger the recording. A shortcut in Quick Settings Panel of android
![Screenshot_4429_1](https://github.com/user-attachments/assets/400c6a33-2c6e-4b20-b92a-de0257e25ffd)

This would make the recording more "clean".

**Comment by HBiSoft** [comment]
My answer in #183 applies to this an well. 

This is app related and not library related.

You can implement this by yourself in your application using a `TileService`.
