### ISSUE TITLE
Stop record cause crash

### ISSUE THREAD

**Issue by vvalladolidIV** [HBiSoft/HBRecorder#2]
When invoke to .stopScreenRecording(data) cause this crash. Attach Android Studio console 
result:

![traza](https://user-images.githubusercontent.com/32733254/65776659-dc340a80-e142-11e9-85e2-c1b95f65b88b.png)

Any idea? 
Thank you very much

**Comment by HBiSoft** [comment]
"When invoke to `.stopScreenRecording(data)` cause this crash." Can you please elaborate?

You should not pass data when stopping the recording, you should only call:

    hbRecorder.stopScreenRecording();

**Comment by vvalladolidIV** [comment]
Yes, of course.
I am working in a Flutter Plugin to screen recorder.
Get to record is all fine but when I try stop it get an exception in FileObserver.
It start and stop recording trought onActivityResult listener, let code:

 ```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean {
        if (requestCode == SCREEN_RECORD_REQUEST_CODE ) {
            if (resultCode == Activity.RESULT_OK) {
                //It is important to call this before starting the recording
                hbRecorder?.onActivityResult(resultCode, data, (registrar.context() as FlutterApplication).currentActivity);
                hbRecorder?.isAudioEnabled(false)
                hbRecorder?.startScreenRecording(data)
            }
        } else if (requestCode == SCREEN_STOP_RECORD_REQUEST_CODE) {
            hbRecorder?.stopScreenRecording()
        }
        return true;
    }
```
Sorry for the ".stopScreenRecording(data)". It was a mistake.

**Comment by HBiSoft** [comment]
Do you set a custom path `hbRecorder?.setOutputPath(path)`?

**Comment by vvalladolidIV** [comment]
I want to do it but I have still do not. Do you think its relationated?

**Comment by vvalladolidIV** [comment]
Yes :) I have set a custom path and all fine. 
Thank you very much.

**Comment by KrushnaNaghate** [comment]
> Yes :) I have set a custom path and all is fine. Thank you very much.


how do you set a custom path, I also need help with issues,

**Comment by MichaelOwen-G** [comment]
how did you use hbrecorder in your flutter application
