### ISSUE TITLE
Display a notification while recording the screen

### ISSUE THREAD

**Issue by MartinMbae** [HBiSoft/HBRecorder#20]
Thanks @HBiSoft  for this wonderful library. 
During recording a notification is not shown despite me having provided the notification icon and the title as well as the Notification message. Where might I be going wrong. 

NOTE: The app is recording the video and saving it to the gallery but not displaying the notification.

**Comment by HBiSoft** [comment]
Does the notification show in the demo application?

**Comment by HBiSoft** [comment]
I will be closing this issue until you let me know if it is working on the demo application.

**Comment by MartinMbae** [comment]
Sorry for the late reply. 
No, I have imported your application as it is, the notification is not working

**Comment by HBiSoft** [comment]
What device and sdk version are you using?

**Comment by MartinMbae** [comment]
I am using Tecno WX3P. Android version 7 API 24

**Comment by MartinMbae** [comment]
Te error was due to using wrong settings. I have reset all the custom settings to DEFAULT and the notification worked. 

Thank you.
I think I now have to close this.
