### ISSUE TITLE
It's possible to record a specific view

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [HBiSoft/HBRecorder#22]
I'm wondering if there's any way to record a specific view or layout instead of recording the whole screen

**Comment by HBiSoft** [comment]
As the library is now, it is not possible. 

I will have to implement a frame processor / `ImageReader` that reads and edits each frame.

I will implement this when this issue gets more attention or if others start asking for this. This will require a lot of work, which I don't currently have time for.

**Comment by ajwad-shaikh** [comment]
@Mouadabdelghafouraitali  I am working on an app that had this requirement, I am simply cropping the video frame to View parameters with FFMPEG for Android. Works fine for me

**Comment by baris-unver** [comment]
@HBiSoft we are also interested in this feature. It would be very useful if could record active screen without top bar and  bottom bar. We are looking forward to an update. Thanks for such a good library!

**Comment by baris-unver** [comment]
> @Mouadabdelghafouraitali I am working on an app that had this requirement, I am simply cropping the video frame to View parameters with FFMPEG for Android. Works fine for me

Hi @Mouadabdelghafouraitali can you please share your solution with me? Thanks!

**Comment by HBiSoft** [comment]
@baris-unver 
As mentioned by @ajwad-shaikh - You can use `FFmpeg` to crop the video to the size of your view.

How you would go about this is to get the height of your `statusbar`, like this:

```java
private int statusBarHeight(android.content.res.Resources res) {
    if(Build.VERSION.SDK_INT < Build.VERSION_CODES.M){
        return (int) (25 * res.getDisplayMetrics().density);
    }else{
        return (int) (24 * res.getDisplayMetrics().density);
    }
}
```

If you have a `NavigationBar` and do not want it in the recording, you should get the height of it as well, like this:
```java
int actionBarHeight = getActionBar().getHeight();
```

You should then add them together:
```java
int topToCrop = statusBarHeight(this.getResources())+actionBarHeight;
```
Now you have the top part that you want to crop.

---

There are many questions regarding cropping using FFmpeg.
[Here](https://github.com/bravobit/FFmpeg-Android) is a `FFmpeg` library for Android.

Hope this helped.

**Comment by goforu** [comment]
Corpping actionBar height using ffmpeg is only applied for portrait mode. However, landscape mode come with lots of complexity. You have to consider camera space, virtual back buttons. And even more, different phone model varies.
