### ISSUE TITLE
HBRecorderOnComplete is called twice for me

### ISSUE THREAD

**Issue by vivek-mittal** [HBiSoft/HBRecorder#24]
HBRecorderOnComplete is called twice for me

I am stopping the recording using 'stopScreenRecording()' api and not the 'Stop recording' button in the notification area. For some unknown reason, HBRecorderOnComplete is called twice. I tried tapping the button in the notification area and the behaviour is the same. HBRecorderOnComplete is called twice. Has anyone else seen the same issue?

**Stack for first call is -** 
callback:308, HBRecorder
run:73, FileObserver$1
handleCallback:883, Handler
dispatchMessage:100, Handler
loop:214, Looper
main:7697, ActivityThread

**Stack for second call is -** 
onReceiveResult:290, HBRecorder$1
run:50, ResultReceiver$MyRunnable
handleCallback:883, Handler
dispatchMessage:100, Handler
loop:214, Looper
main:7697, ActivityThread

I have followed the instructions to integrate the library from [here](https://github.com/HBiSoft/HBRecorder).

**Comment by HBiSoft** [comment]
My apologies for the late reply. I noticed something similar over the weekend. I believe it is related to how I call the `onCompleteListener`. Can you please confirm if you are passing a file path or an `uri` to the library?

**Comment by vivek-mittal** [comment]
Glad to hear back from you. Currently I am not passing any uri to the library and only fetching it in HRRecorderOnComplete(). I was planning to provide a custom path, but it is not as important as this issue.

**Comment by HBiSoft** [comment]
@vivek-mittal 
I found the issue and I will be updating the library in the next 10 min.

**Comment by HBiSoft** [comment]
@vivek-mittal 
This should be fixed in `0.1.12`.
You can test it and if it is fixed, please close the issue.

**Comment by vivek-mittal** [comment]
Thanks Hagen. I will test them and let you know.

**Comment by HBiSoft** [comment]
I assume this is fixed, feel free to reopen the issue if not.

**Comment by vivek-mittal** [comment]
I just checked and this issue is fixed. Thanks a ton.
