### ISSUE TITLE
"Unable to screen record" toast

### ISSUE THREAD

**Issue by alexrad89** [HBiSoft/HBRecorder#26]
After implementing the class and starting a screen recording, the app kicks out of my recording screen and a toast message comes up with "Unable to screen record". What could be causing this?

![20200904_143441](https://user-images.githubusercontent.com/4390213/92279037-07c78500-eebc-11ea-9235-5c936f5f30fa.jpg)

**Comment by HBiSoft** [comment]
You are probably trying to record an application which has `window.setFlags(WindowManager.LayoutParams.FLAG_SECURE` set.

If the secure flag is set by some application, you will not be able to record that application.

**Comment by HBiSoft** [comment]
I will be closing this issue since there is nothing I can do about this. 

If you find that the `Toast` does not get displayed when you have another application open, feel free to reopen the issue and provide more information regarding your implementation, scenario etc.
