### ISSUE TITLE
Audio not recording in android 10 when i set audio source to 'DEFAULT'

### ISSUE THREAD

**Issue by Rja-123** [HBiSoft/HBRecorder#28]
Before filing a bug:
-----------------------
- Please fill in all the information below.
- Have a look at previously asked questions to see if your issue has been resolved.
- Properly format your issue.
- All issues should be asked in English.
- Delete all the above before posting your issue

**Describe the bug**

**Log**
Please provide a well formatted bug report (by adding 4 spaces before the log)

**Can it be reproduced in demo app**
Yes or no

**HBRecorder version**
for example 1.0.1

**Device information**
- Make/model
- SDK version

**Screenshots**

**Comment by HBiSoft** [comment]
Please edit your question and fill out the issue template. Closing the issue for now.
