### ISSUE TITLE
Audio not recorded when i use it during call android 10

### ISSUE THREAD

**Issue by Rja-123** [HBiSoft/HBRecorder#29]
Before filing a bug:
-----------------------
- Have a look at previously asked questions to see if your question has been asked before.
- Properly format your question.
- All questions should be asked in English.
- Questions that are not related to the project will be deleted
- Delete all the above before posting

**Comment by HBiSoft** [comment]
You opened an [issue](https://github.com/HBiSoft/HBRecorder/issues/28) 2 days ago and I asked you to fill out the issue template. Now you open another issue and you still did not fill in the issue template??

**Comment by HBiSoft** [comment]
Have a look at this answer - https://stackoverflow.com/a/58545010/5550161

To be able to record audio from two sources, an `Accessibility Service` should be used (in combination with an `Accessibility Overlay`), plus the audio input source should be `VoiceRecognition`. This, for me, seems like an overkill and I honestly don't have time to change the entire library for something that was never intended to be a part of the library.
