### ISSUE TITLE
some video recorded using library can not be skipped while playing in android emulator ?

### ISSUE THREAD

**Issue by chiragthummar** [HBiSoft/HBRecorder#32]
i have been recording screen using library but when i test this app in android emulator , video play in default android player in emulator video is not skippable. so is there any problem with the video codec or other problem ?
so please solve this problem.
thank you.

**Comment by HBiSoft** [comment]
Android emulator has never been reliable with testing video. I suggest you test with an actual device.

[You could also](https://stackoverflow.com/a/63928538/5550161) enable `Hardware - GLES 2.0` in your emulator's performance settings:

>open the AVD manager, scroll down to emulated performance, change it from "Automatic" to "Hardware - GLES 2.0", if still not performing show the advanced settings and set it to "Cold boot" this changed it from like 8-12 fps to a solid 30 fps non stop.

---

I have tested it on multiple devices and I can seek through the video with all of them. So, this is related to emulator and not the library.
