### ISSUE TITLE
video recording not starting in android Lollipop ?

### ISSUE THREAD

**Issue by chiragthummar** [HBiSoft/HBRecorder#33]
it just gives simple error while start recording in it.

`HBRecorderOnError: 268435556`

**Comment by chiragthummar** [comment]
on other version it works fine

**Comment by HBiSoft** [comment]
Please see [Always fill in the issue template](https://github.com/HBiSoft/HBRecorder/issues/31)

**Comment by chiragthummar** [comment]
but logcat not showing other log which i can post here.
it just give simply error above.

**Comment by HBiSoft** [comment]
Does this happen using the demo application?
Do you start the recording from your application or a service?
Do you have any application open when starting the recording?

**Comment by chiragthummar** [comment]
have used demo application which is provided in lib and starting recording from the service as given in example.
nothing changed. and also when i start app it just goes in ANR .

**Comment by chiragthummar** [comment]
HBRecorder throwing error because of the directory is not created in emulator .

**Comment by HBiSoft** [comment]
I have tested it on a physical device running lollipop and I can't reproduce this. I believe it could be related to the emulator. I'm closing the issue for now. If you can reproduce this on a physical device, please reopen the issue.
