### ISSUE TITLE
Support for internal audio recording

### ISSUE THREAD

**Issue by kunwar97** [HBiSoft/HBRecorder#35]
Does it support internal audio recording?

**Comment by sutanurath** [comment]
Android does not support internal audio recording but this library record audio from micro phone. This library support properly sync video with audio.

**Comment by HBiSoft** [comment]
This is possible on Android 10 using the new [AudioPlaybackCapture](https://developer.android.com/guide/topics/media/playback-capture) API. I will have a look at it over the weekend.
