### ISSUE TITLE
how can i crop video which is captured by recorder ?

### ISSUE THREAD

**Issue by chiragthummar** [HBiSoft/HBRecorder#36]
i am trying to record a video in cropped screen but not able to do so far.
so is there any idea or code which  can be implemented so that capture screen can be cropped while recording.

i have changed code as below

` mMediaRecorder.setVideoSize(mScreenWidth, mScreenHeight);`

but not get desirable output.

so if there any solution please tell me.

**Comment by HBiSoft** [comment]
This library doesn't include any video encoding/decoding or cropping, you will have to implement that yourself with something like [FFmpeg](https://github.com/tanersener/mobile-ffmpeg) or [Transcoder](https://github.com/natario1/Transcoder).

---

```java
mMediaRecorder.setVideoSize(mScreenWidth, mScreenHeight);
```
This sets the size of the output video, it doesn't crop it.
