### ISSUE TITLE
how i can install it as system app ?

### ISSUE THREAD

**Issue by abasgames** [HBiSoft/HBRecorder#37]
hello i have device that running lineage os 17.1 i would like to replace the stock recorder app with this app i have magisk root and twrp if thats help the reason i would install it as system app are because theres some apps doesn't updated long time ago and you can't record them with internal audio if you installed the apk as user app

**Comment by HBiSoft** [comment]
I'm sorry but I have no experience with LineageOS or installing system application.
You will have to do your own research on how to do this.

This is a library intended to be used by developers. The app itself is only a demonstration of what the library can do.

I hope you find a solution.
