### ISSUE TITLE
saved video is not playing on android 8 in 4.4.4 it work fine 

### ISSUE THREAD

**Issue by zubairrahmani** [HBiSoft/HBRecorder#4]

**Comment by HBiSoft** [comment]
There is no way for me to even start debugging the issue with the information you have provided.

Can you reproduce this in the demo app?
Does it happen with SD and HD recording?
What version are you using?

Side note - it should not be working on 4.4.4. MediaProjection API was introduced in Android 5 (API 21 - Lollipop) - https://developer.android.com/reference/android/media/projection/MediaProjection

**Comment by zubairrahmani** [comment]
It's work on my android phone 4.4.4
But in my Android 8.1.0 it record the video but video is not playing  thanks

**Comment by HBiSoft** [comment]
I'm closing this issue until you can provide more information.
