### ISSUE TITLE
Help,Screen capture while recording

### ISSUE THREAD

**Issue by chen412115** [HBiSoft/HBRecorder#40]
Is it supported

**Comment by HBiSoft** [comment]
Yes, but you will not be able to record audio while the microphone is in use.

**Comment by chen412115** [comment]
How should i do

**Comment by HBiSoft** [comment]
Have a look at this answer - https://stackoverflow.com/a/58545010/5550161

To be able to record audio from two sources, an Accessibility Service should be used (in combination with an Accessibility Overlay), plus the audio input source should be VoiceRecognition.

---
Even doing the above, you have no guarantee it will work on all devices.

**Comment by chen412115** [comment]
yeah  ,thank you
