### ISSUE TITLE
Get Continue Recording Without Permisison ?

### ISSUE THREAD

**Issue by GauravMandlikSafecode** [HBiSoft/HBRecorder#41]
![device-copy](https://user-images.githubusercontent.com/73181121/98950837-81fd3100-251f-11eb-9da8-ec0d384f7fc8.png)

can i start recording without permission popup in app,my point is can i get store intent in app. i check in android 10 device that prompt every time when i start recording.

Thanks.

**Comment by HBiSoft** [comment]
No you cannot.

**Comment by GauravMandlikSafecode** [comment]
Hi @HBiSoft 


Please check this app it's already available in Play Store, it is possible [https://play.google.com/store/apps/details?id=videoeditor.videorecorder.screenrecorder](url)

**Comment by HBiSoft** [comment]
They are probably still targeting API level 28. The developer will have to target 29 in the next update (since the minimum [API level is now 29](https://developer.android.com/distribute/best-practices/develop/target-sdk)) and then you will see the same notification popup.

**Comment by GauravMandlikSafecode** [comment]
@HBiSoft 


Then how about working in android Api Level 29 or 30.

Thanks.
