### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by cristea2017** [HBiSoft/HBRecorder#42]
i come here from : https://morioh.com/p/11b23bb6f978

i am wondering can we use this lib to share screen to twitch for example ? (to stream video exactly)
as screen recording works perfectly thanks a lot ;)

**Comment by HBiSoft** [comment]
This [should be possible](https://stackoverflow.com/a/40649258/5550161) by passing the `LocalSocket`'s file descriptor to the library - `hbrecorder.setOutputPath(localSocket.getFileDescriptor());` I have not tested it, but I'm sure it will work.

**Comment by wznshuai** [comment]
nice
