### ISSUE TITLE
HBRecorder recording stucks on API equal to or less then 23 (Android Level equal to or below then 6)

### ISSUE THREAD

**Issue by arsalanraja26** [HBiSoft/HBRecorder#48]
Hi, I am working on API level 23 (Android version 6.0) 
I have to record screen and also take screenshot on the same activity/screen (having exoplayer for playing video).
when I only record screen or only take screenshot then everything is working perfectly
but
when I start screen recording and while in screen recording I take screenshot then after that the screen recording stucks, 
note that for screenshot I am using media projection with different instance and API level higher then 23 are working perfectly, I am facing issue only in 23 and less than 23.
Also, I am attaching screenshot for better understanding and if you still need more information then ask me..
In first screenshot I am just recording screen and everything is perfect
In second screenshot when I take screenshot then dialog appears and when I select start now then screen recording stucks as you can see in third screenshot

![Screenshot_2020-11-30-16-18-52](https://user-images.githubusercontent.com/56070586/100604551-83549900-3328-11eb-95f6-96a297238eaf.png)

![Screenshot_2020-11-30-16-19-03](https://user-images.githubusercontent.com/56070586/100604634-9a938680-3328-11eb-8a50-d986a7f6bb40.png)

![Screenshot_2020-11-30-16-19-15](https://user-images.githubusercontent.com/56070586/100604646-a2532b00-3328-11eb-90d6-c159f7bd31f2.png)

**Comment by arsalanraja26** [comment]
@HBiSoft Kindly Help me as soon as possible

**Comment by HBiSoft** [comment]
I think the issue is that your device can't have multiple instances of `MediaProjection` along with `MediaCodec` (which ExoPlayer is using).

I will be adding the ability to take screenshots using the library in the next few days, but I can't guarantee that you will be able to take screenshots while recording, especially on older devices
