### ISSUE TITLE
I am unable to import dependency

### ISSUE THREAD

**Issue by Vexturbo** [HBiSoft/HBRecorder#49]
**Describe the bug**
I am unable to import HBRecorder:0.1.15.

**Log**

Failed to resolve: com.github.HBiSoft:HBRecorder:0.1.15
Show in Project Structure dialog
Affected Modules: app

**Can it be reproduced in demo app**
no

**HBRecorder version**
0.1.15

**Device information**
defaultConfig
minSdkVersion 16
targetSdkVersion 29
versionCode 1
versionName "1.0"
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

**Comment by HBiSoft** [comment]
Please see the instructions - https://github.com/HBiSoft/HBRecorder#adding-the-library-to-your-project

If you still have this issue after following the instructions, provide both your gradle files.
