### ISSUE TITLE
Add Remote_Submix support

### ISSUE THREAD

**Issue by SGNight** [HBiSoft/HBRecorder#52]
**Is your feature request related to a problem? Please describe.**
I'm testing this app on android-x86 7.1 it's working good so far but i want to use the remote_submix as audio source so that i can record the internal audio. my custom android x86 build does support this feature but only app i can't find use this feature is ScreenCam Screen recorder but it's no longer under development & have many bugs with android x86. 
**Describe the solution you'd like**
if you can add r_submix support like screencam it'll be great.
https://gitlab.com/vijai/screenrecorder
thanks

**Comment by HBiSoft** [comment]
This is already possible. 

Have a look at the readme (at the bottom). You first have to enable custom settings, like this:

```java
hbRecorder.enableCustomSettings();
```

Then you can set the audio source:

```java
//MUST BE ONE OF THE FOLLOWING - https://developer.android.com/reference/android/media/MediaRecorder.AudioSource.html
hbRecorder.setAudioSource(String);
```
In your case it will be:

```java
hbRecorder.setAudioSource("REMOTE_SUBMIX");
```

**Comment by SGNight** [comment]
thank you so much for you reply.
 i've tested this on demo app by replacing "REMOTE_SUBMIX" with "CAMCODER" and it works like charm.
 i would suggest you to put all the settings of the app in main activity in stead of setting since default HD & SD menu seems pretty useless to me.
 i'll do some more testing & on my other builds & report you back if i find any bug.
Cheers 😄
