### ISSUE TITLE
Getting file not found exception

### ISSUE THREAD

**Issue by mitulghoda** [HBiSoft/HBRecorder#54]
Sometimes i got file not found exception, 
i am setting my own path and file name.

private fun setOutputPath() {
        val filename: String = generateFileName()!!
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
             resolver = contentResolver
             contentValues = ContentValues()
             contentValues!!.put(
                 MediaStore.Video.Media.RELATIVE_PATH,
                 "Movies/." + getString(R.string.app_name)
             )
             contentValues!!.put(MediaStore.Video.Media.TITLE, filename)
             contentValues!!.put(MediaStore.MediaColumns.DISPLAY_NAME, filename)
             contentValues!!.put(MediaStore.MediaColumns.MIME_TYPE, "video/mp4")
             mUri = resolver!!.insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, contentValues)
             //FILE NAME SHOULD BE THE SAME
             hbRecorder!!.fileName = filename
             hbRecorder!!.setOutputUri(mUri)
             Log.e("VideoPath-10", RealPathUtil.getRealPath(mContext, mUri))

             formModel!!.screen_recording = RealPathUtil.getRealPath(mContext, mUri)
           /* val strPath =
                MediaType.getRootDirectory(mContext, MediaType.VIDEO) + "/SD" + filename + ".mp4"
            Log.e(
                "FileUtilsPath-10>>", strPath

            )
            Log.e(
                "FileUtilsPath-Root-10->>>",
                MediaType.getRootDirectory(mContext, MediaType.VIDEO)
            ).toString()
            hbRecorder!!.fileName = filename
            hbRecorder!!.setOutputPath(
                MediaType.getRootDirectory(mContext, MediaType.VIDEO)
            )
            formModel!!.screen_recording = strPath*/
        } else {
            createFolder()
            val strPath =
                MediaType.getRootDirectory(mContext, MediaType.VIDEO) + "/SD" + filename + ".mp4"
            Log.e(
                "FileUtilsPath->>", strPath

            )
            Log.e(
                "FileUtilsPath-Root>>",
                MediaType.getRootDirectory(mContext, MediaType.VIDEO)
            ).toString()

            hbRecorder!!.setOutputPath(
                MediaType.getRootDirectory(mContext, MediaType.VIDEO)
            )
            formModel!!.screen_recording = strPath
        }
    }

**Comment by HBiSoft** [comment]
This is not related to the library. You are passing an invalid file path to the library. You can make use of my other library (PickiT) if you want to pass a valid file path when selecting a file from `Mediastore`

**Comment by fukemy** [comment]
hi, did u solved this? THanks
