### ISSUE TITLE
screen recording in android 11 takes 4 second to start ?

### ISSUE THREAD

**Issue by chiragthummar** [HBiSoft/HBRecorder#57]
hello
i have been using your lib in my application, but when i set target sdk 30 and tried it but it takes 4 to 5 seconds to start recording.
so what is the problem? i have tried but not getting any idea of it.

please tell me about it.

i have been using `android:requestLegacyExternalStorage="true"` in manifest.

**Comment by HBiSoft** [comment]
I was not able to reproduce this. Please provide more information. What device are you using? Are you testing on an emulator? Add a log in `HBRecorderOnStart()` and check if it is called immediately or after 4 seconds.
