### ISSUE TITLE
Video & Audio are out of sync

### ISSUE THREAD

**Issue by kunwar97** [HBiSoft/HBRecorder#58]
**Describe the bug**
When recording screen while doing video call there is slight delay in audio

**Can it be reproduced in demo app**
Yes

**HBRecorder version**
for example 0.1.15

**Device information**
- Asus Rog Phone 3
- Sdk Version 29

**Screenshots**
![Screenshot_20210324-122414538](https://user-images.githubusercontent.com/20859901/112267848-129d0800-8c9c-11eb-8830-2bc2dc7f9f54.jpeg)

**Comment by HBiSoft** [comment]
This is to be expected. From the [docs](https://developer.android.com/guide/topics/media/sharing-audio-input#pre-behavior):

>Before Android 10 the input audio stream could only be captured by one app at a time. If some app was already recording or listening to audio, your app could create an AudioRecord object, but an error would be returned when you called AudioRecord.startRecording() and the recording would not start.

>One exception to this rule was when a privileged app (like Google Assistant or an accessibility service) had the permission android.permission.CAPTURE_AUDIO_HOTWORD and used an audio source of type HOTWORD. In this case another app could start recording. When that happened the privileged app terminated and the new app captured the input.

You might be able to record audio from 2 sources on your specific device, but you can't expect it to work on other devices running 29<.

Unfortunately there is nothing I can do about this.
