### ISSUE TITLE
Recorded videos sometimes show black, or pixelated portions

### ISSUE THREAD

**Issue by tfrysinger** [HBiSoft/HBRecorder#63]
**Describe the bug**
Recording using SD with sound (otherwise all standard settings), I have seen some instances where either the screen shows blank (but sound is there), or portions of the screen are pixelated. Other times it works fine.

I've created a folder on Dropbox with two sample videos in it [here](https://www.dropbox.com/sh/pk5s943sltnxcny/AABXyIkKocU6y_F8yAlNYkFPa?dl=0).

**Can it be reproduced in demo app**
No - seems to be device specific

**HBRecorder version**
for example 0.1.15

**Device information**
- Make/model: Google Nexus 9 was the device where the screen was recorded, playing the subsequent video on a Windows PC or iPhone was where the problem was noticed.
- SDK version: API 23

**Comment by tfrysinger** [comment]
More information - the output .mp4 files play fine on a Windows machine, but not on an iOS machine (i.e. 10.x apple phone)

**Comment by HBiSoft** [comment]
@tfrysinger 
It looks like the video uses h.264 Main Profile level 5.1, while iOS only supports AVC level 3.1
Unfortunately, there is not much I can do on my side as your device selects the best codec and the selected codec is not supported on the device you are playing it on.

You can decode the video before saving/sharing it. Have a look at [Transcoder](https://github.com/natario1/Transcoder).

**Comment by tfrysinger** [comment]
Thanks, will take a look.

T
