### ISSUE TITLE
HBRecoder is crashing on nokia devices.

### ISSUE THREAD

**Issue by jhon313** [HBiSoft/HBRecorder#64]
**Describe the bug**
App is crashing on start button , a toast appears of text"Some thing not supporting by your device" and did not start recording fully stop. 

**Log**

com.hbisoft.hbrecorderexample E/GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
/com.hbisoft.hbrecorderexample E/HBRecorder: HBRecorderOnStart called
/com.hbisoft.hbrecorderexample E/GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false

**Can it be reproduced in demo app**
Ye

**HBRecorder version**
 1.0

**Device information**
- Nokia/Nokia 5.1 plus
- SDK version 30

**Comment by HBiSoft** [comment]
@jhon313 
Please try the latest release `0.1.16`, if the issue continues, please provide me the log.
