### ISSUE TITLE
Saved video with only 0kb

### ISSUE THREAD

**Issue by Namdh1212** [HBiSoft/HBRecorder#65]
I am testing on Android 5.1 then save the video with only 0kb
Android 10 sometimes fails

Can it be reproduced in demo app
Yes

HBRecorder version
for example 0.1.15

**Comment by Namdh1212** [comment]
I am testing on Android 5.1 then save the video with only 0kb
Android 10 sometimes fails

Can it be reproduced in demo app
Yes

HBRecorder version
for example 0.1.15

**Comment by HBiSoft** [comment]
@Namdh1212 
If you are still experiencing this issue, please provide me the log.
Also, you should test on a physical device and not an emulator.
