### ISSUE TITLE
Is selling this app / library with small changes allowed ?

### ISSUE THREAD

**Issue by SGNight** [HBiSoft/HBRecorder#67]
I was doing some random google search & found this guy was selling source code of an app but when i check his screenshot i knew he was using using HBR source code and i downloaded his demo app which later confirms my doubts.
![image](https://user-images.githubusercontent.com/62793442/116858875-bcb56b80-ac1c-11eb-9e04-c6181047aaaf.png)

Link for the post 

https://www.codester.com/items/30595/easy-screen-recorder-with-audio-google-admob

so i want to ask this is using this app / library in your project without credit allowed ?
and is selling this app on play store or any other website allowed ?

if not what actions you are going to take against these guys.

**Comment by HBiSoft** [comment]
Thank you for reporting this. This is allowed as long as he/she is releasing it with the correct license. I encourage users to donate if they are making money using my library.
