### ISSUE TITLE
Is there a method to set max recording time limit programtically?

### ISSUE THREAD

**Issue by ali0094** [HBiSoft/HBRecorder#68]
Before filing a bug:
-----------------------
- Have a look at previously asked questions to see if your question has been asked before.
- Properly format your question.
- All questions should be asked in English.
- Questions that are not related to the project will be deleted
- Delete all the above before posting

**Comment by HBiSoft** [comment]
@ali0094 In the latest release you can set the max file size. You can use a timer if you want to set the max recording time for now.

I implement this over the weekend.

**Comment by HBiSoft** [comment]
This is now possible in version `2.0.0` using `hbRecorder.setMaxDuration(int);`. Provide the max duration in seconds.

Thanks for the suggestion.
