### ISSUE TITLE
What is error code 38 and 268435556 stands for?

### ISSUE THREAD

**Issue by TehleelMir** [HBiSoft/HBRecorder#70]
it worked fine on android O but when I run the same code on android P it pop up error message with code 38 and 268435556

**Comment by HBiSoft** [comment]
Please provide your settings used when the crash happens.

This is most probably because you are passing settings that's not supported by your device.

**Comment by TehleelMir** [comment]
i tried to set all possible setting on their lowest value but it still poped the same thing

**Comment by HBiSoft** [comment]
Closing until more information is provided. As the question stands now, it could be anything causing this.

**Comment by HBiSoft** [comment]
If more information was provided, I would've been able to help.

https://github.com/HBiSoft/HBRecorder/blob/a8207fe6b05f0a7701516ad83e881403e491130b/hbrecorder/src/main/java/com/hbisoft/hbrecorder/ScreenRecordService.java#L302

`268435556` is an error code from `MediaRecorder` and not the library.

**Comment by Mhmetengineer** [comment]
@HBiSoft error this line.. => https://ibb.co/9sXgzsC

**Comment by Mhmetengineer** [comment]
Solved this problem.. @TehleelMir  ...
Our device not supported default video encoder.. 
H264 , H263, HEVC, MPEG_4_SP OR VP8 
My device support HEVC .  
 hbRecorder.setVideoEncoder("HEVC");  working in my project..

**Comment by HBiSoft** [comment]
You can make use of the `HBRecorderCodecInfo.java` class, as shown in the demo application, to check what settings and encoder is supported and then make the changes accordingly:

https://github.com/HBiSoft/HBRecorder/blob/a8207fe6b05f0a7701516ad83e881403e491130b/app/src/main/java/com/hbisoft/hbrecorderexample/MainActivity.java#L137-L173

**Comment by akashappscale** [comment]
HBRecorderOnError error code 38 

    implementation 'com.github.HBiSoft:HBRecorder:3.0.1'
