### ISSUE TITLE
Video recording not working for android 6 , stops immediately

### ISSUE THREAD

**Issue by friendscorpgroup** [HBiSoft/HBRecorder#71]
**Describe the bug**
Library works well with other versions android 9 and 10 tested , but on android 6 recorder starts but getting stopped immediately with file generated of some KBs  in storage directory , not playable .

**Log**
MainActivity: errorcode : 38 reason : 268435556

 E/HBRecorderCodecInfo: defaultVideoEncoder for (video/avc) -> OMX.MTK.VIDEO.ENCODER.AVC
 E/HBRecorderCodecInfo: MaxSupportedFrameRate -> 0.0
 E/HBRecorderCodecInfo: MaxSupportedBitrate -> 62500000
 E/HBRecorderCodecInfo: isSizeAndFramerateSupported @ Width = 1080 Height = 1920 FPS = 30 -> false
 E/HBRecorderCodecInfo: isSizeSupported @ Width = 1080 Height = 1920 -> false
 E/HBRecorderCodecInfo: Default Video Format = MPEG_4
 E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.MTK.VIDEO.ENCODER.H263 -> video/3gpp
 E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.mpeg4.encoder -> video/mp4v-es
 E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.h264.encoder -> video/avc
 E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.MTK.VIDEO.ENCODER.MPEG4 -> video/mp4v-es
 E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.h263.encoder -> video/3gpp
 E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.MTK.VIDEO.ENCODER.AVC -> video/avc
 E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.vp8.encoder -> video/x-vnd.on2.vp8
 E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.MTK.AUDIO.ENCODER.VORBIS -> audio/vorbis
 E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.MTK.AUDIO.ENCODER.ADPCM.DVI -> audio/x-adpcm-dvi-ima
 E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.flac.encoder -> audio/flac
 E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.aac.encoder -> audio/mp4a-latm
 E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.amrwb.encoder -> audio/amr-wb
 E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.amrnb.encoder -> audio/3gpp
 E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.MTK.AUDIO.ENCODER.ADPCM.MS -> audio/x-adpcm-ms
 E/HBRecorderCodecInfo: Available Video Formats : MPEG_2_TS
 E/HBRecorderCodecInfo: Available Video Formats : MPEG_4
 E/HBRecorderCodecInfo: Available Video Formats : THREE_GPP
 E/HBRecorderCodecInfo: Available Video Formats : WEBM

**Can it be reproduced in demo app**
Yes

**HBRecorder version**
2.0.0

**Device information**
- Lenove A7010
- SDK version 23 ( android 6.0)

**Extra Info**
checked isframesupported() method with all of available mimetype and also with reduced width n height , and got FALSE for all types.

**Comment by HBiSoft** [comment]
Please try and set the width/height to:

Width = 1920 Height = 1080

Instead of:

Width = 1080 Height = 1920

**Comment by friendscorpgroup** [comment]
it gives FALSE for that method , tried different values
isSizeAndFramerateSupported @ Width = 1920 Height = 1080 FPS = 30 -> false
isSizeAndFramerateSupported @ Width = 1920 Height = 1080 FPS = 20 -> false
isSizeAndFramerateSupported @ Width = 1080 Height = 1920 FPS = 20 -> false
sSizeAndFramerateSupported @ Width = 540 Height = 960 FPS = 20 -> false

**Comment by HBiSoft** [comment]
That's strange. I can give a few recommendations that you can try.

1. First, check on the demo application if this occurs when selecting quick settings (not custom settings)
2. If that fails, select "Use custom settings", select the menu and set the video encoder to either "H254", "H263" or "MPEG_4_SP.
3. If that fails, set the output format to "Default".

For some reason your encoder doesn't want to accept the size provided, even if it is supported by your device. That's why I want you to check if using a different encoder fixes the issue.

**Comment by friendscorpgroup** [comment]
Yes , it works with "H264" Encoder from custom settings , "default" doesn't work. So can you please suggest if I can use hbRecorder.setVideoEncoder("H264"); for all then Or if i need to check isSizeAndFramerateSupported with different encoders is there any method ?
