### ISSUE TITLE
Android 11 recordings are corrupted sometimes

### ISSUE THREAD

**Issue by Charles0115** [HBiSoft/HBRecorder#78]
**Describe the bug**
This bug is best described by a video. The bug is this: when I finish recording and go into "File". The video in "Video" section can be played, but the video in "The internal storage" cannot. Sometimes it happens, sometimes not. 
Youtube Link: https://youtu.be/ujidZIHkTus
![Screenshot_20210711-170330](https://user-images.githubusercontent.com/44145778/125209962-ac4bed80-e26a-11eb-8034-cb3738d35bae.png)
![Screenshot_20210711-170355](https://user-images.githubusercontent.com/44145778/125209963-ac4bed80-e26a-11eb-9e15-546dde663c96.png)

**Can it be reproduced in demo app**
Yes

**HBRecorder version**
latest

**Device information**
- Make/model: Google Pixel 5
- SDK version: 30

**Screenshots**

**Comment by HBiSoft** [comment]
Just to check, can you restart your device and see if the videos are playable then.

**Comment by Charles0115** [comment]
I couldn't reproduce one right now, like I said it's a chance thing. I'll keep trying. 
Maybe because MANAGE_EXTERNAL_STORAGE permission affects the library.

**Comment by HBiSoft** [comment]
`the issue occurred again. I restarted and this time the video is playable as normal. Strange`

The issues seems to be with the updating/refreshing of the created file and not directly related to the library:

https://github.com/HBiSoft/HBRecorder/blob/a8207fe6b05f0a7701516ad83e881403e491130b/app/src/main/java/com/hbisoft/hbrecorderexample/MainActivity.java#L292-L297

I'm not sure why this is happening. I will look into it..

**Comment by Charles0115** [comment]
The issue persists. 
One thing to notice is that videos from two different places have different sizes. 

![Screenshot_20210717-135001](https://user-images.githubusercontent.com/44145778/126045696-ec399643-bc86-4fcc-9211-3f1169c09e82.png)
![Screenshot_20210717-134946](https://user-images.githubusercontent.com/44145778/126045703-681c32aa-93f6-4cae-a333-f04d897f6941.png)
