### ISSUE TITLE
Android 11 WRITE_EXTERNAL_STORAGE permission no longer works

### ISSUE THREAD

**Issue by Charles0115** [HBiSoft/HBRecorder#79]
According to Google, 
If your app targets Android 11, both the WRITE_EXTERNAL_STORAGE permission and the WRITE_MEDIA_STORAGE privileged permission no longer provide any additional access.

This causes the app cannot start recording in Android 11.

**Comment by HBiSoft** [comment]
Where does this library use `WRITE_EXTERNAL_STORAGE`?

**Comment by Charles0115** [comment]
checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE, PERMISSION_REQ_ID_WRITE_EXTERNAL_STORAGE))

**Comment by Charles0115** [comment]
The recording can be started when I remove the EXTERNAL_STORAGE permission, but this issue occurs. 
https://github.com/HBiSoft/HBRecorder/issues/78

**Comment by HBiSoft** [comment]
Ok, `Manifest.permission.WRITE_EXTERNAL_STORAGE` can be removed. I must have forgotten to remove it when updating the `targetSdkVersion` to 30. I will remove it in the next release.

As for the other issue, I will comment there.
