### ISSUE TITLE
Add   android:foregroundServiceType="mediaProjection"  Service tag under manifest for Android Pie and Android Q support also    android:requestLegacyExternalStorage="true"  in application tag for android 10 storage permission.

### ISSUE THREAD

**Issue by Mirzaali-innovagictechnologies** [HBiSoft/HBRecorder#8]
Before filing a bug:
-----------------------
- Please fill in all the information below.
- Have a look at previously asked questions to see if your issue has been resolved.
- Properly format your issue.
- All issues should be asked in English.
- Delete all the above before posting your issue

**Describe the bug**

**Log**
Please provide a well formatted bug report (by adding 4 spaces before the log)

**Can it be reproduced in demo app**
Yes or no

**HBRecorder version**
for example 1.0.1

**Device information**
- Make/model
- SDK version

**Screenshots**

**Comment by HBiSoft** [comment]
Please format your question properly (describing the issue as the bug template states) and providing a proper title.
---

Currently, this library is targeting API 28, so there is no need to add `android:foregroundServiceType="mediaProjection"`. If you wanted me to increase the target API, then it should have been your question.

As for the `android:requestLegacyExternalStorage="true"`: 
It is not up to the library to add this. Your application is providing the destination path, so you should add it in your manifest.

---
You can reopen this issue after reformating it or open a new issue.

**Comment by HBiSoft** [comment]
I have migrated the library to Android 10 (API 29). [Here is the release](https://github.com/HBiSoft/HBRecorder/releases/tag/0.1.7)
