### ISSUE TITLE
Add Android Q support

### ISSUE THREAD

**Issue by osfunapps** [HBiSoft/HBRecorder#9]
Hey,
Great library!

There is an issue with:
`getExternalStoragePublicDirectory()` is no longer supported starting Android Q and forward.

Can you add a way to do this? I suggest to use:

```
      val resolver = context.contentResolver
      val contentValues = ContentValues().apply {
        put(MediaStore.MediaColumns.DISPLAY_NAME, "CuteKitten001")
        put(MediaStore.MediaColumns.MIME_TYPE, "image/jpeg")
        put(MediaStore.MediaColumns.RELATIVE_PATH, "DCIM/PerracoLabs")
      }

      val uri = resolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, contentValues)

      resolver.openOutputStream(uri).use {
        // TODO something with the stream
      
```
But probably with the props the user set.

The answer is from here:
[https://stackoverflow.com/questions/20523658/how-to-create-application-specific-folder-in-android-gallery](https://stackoverflow.com/questions/20523658/how-to-create-application-specific-folder-in-android-gallery)

**Comment by osfunapps** [comment]
oops sorry. Saw just now that this library is not maintainable anymore for future devices. 

Thanks!

**Comment by HBiSoft** [comment]
@osfunapps 
"Saw just now that this library is not maintainable anymore for future devices."

This is not true. I will increase the API version (hopefully today).
I wanted to wait for the Android R release before doing this.

**Comment by HBiSoft** [comment]
I have migrated the library to Android 10 (API 29). [Here is the release](https://github.com/HBiSoft/HBRecorder/releases/tag/0.1.7)

**Comment by osfunapps** [comment]
Great! You surely have a great library man!

**Comment by HBiSoft** [comment]
@osfunapps 
I thought I would let you know that you can now pass a `Uri` instead of a file path on devices running Android Q>.

Have a look at how I implemented it into the demo project:

https://github.com/HBiSoft/HBRecorder/blob/ad75b18810719ba7c71b882fa5eae4875afeb9a3/app/src/main/java/com/hbisoft/hbrecorderexample/MainActivity.java#L527-L548
