### ISSUE TITLE
App crashes as soon as i start video recording

### ISSUE THREAD

**Issue by ShizaS** [HBiSoft/HBRecorder#93]
**Problem**
I have integrated the library in my app and I followed the document while integrating. The issue is as soon as I press start recording on the pop up the app crashes.

**Error**
E/MediaRecorder: SurfaceMediaSource could not be initialized!
E/MediaRecorder: start called in an invalid state: 32

**HBRecorder version**
2.0.1

**Device information**
- Xiaomi 9T
- android version 10

**Comment by ShizaS** [comment]
@HBiSoft thanks for the quick response. Demo app is working fine now.

**Comment by HBiSoft** [comment]
@ShizaS 
Thanks for letting me know.
