### ISSUE TITLE
I'm facing this issue Failed to resolve: com.github.HBiSoft:HBRecorder:2.0.2

### ISSUE THREAD

**Issue by saudkhan488** [HBiSoft/HBRecorder#95]
I'm facing this issue
Failed to resolve: com.github.HBiSoft:HBRecorder:2.0.2

**Comment by saudkhan488** [comment]
Failed to resolve: com.github.HBiSoft:HBRecorder:2.0.2

**Comment by HBiSoft** [comment]
Did you add the following in your root `build.gradle'?

```xml
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }	    
    }
}
```

**Comment by HBiSoft** [comment]
I'm closing this issue since it's not related to the library. You can have a look at the read me to see how to implement the library into your project.
