### ISSUE TITLE
how i can record internal audio ?

### ISSUE THREAD

**Issue by kamaljeeta6221** [HBiSoft/HBRecorder#97]
Before filing a bug:
-----------------------
- Have a look at previously asked questions to see if your question has been asked before.
- Properly format your question.
- All questions should be asked in English.
- Questions that are not related to the project will be deleted
- Delete all the above before posting

**Comment by HBiSoft** [comment]
I will pin this issue for other users to see in the future. This question has been asked a couple of times. 

As the library is now, it is not possible. You can have a look at the [AudioPlaybackCapture API](https://developer.android.com/guide/topics/media/av-capture#capture_audio_playback). Apparently, using this API, you will be able to record internal audio / audio from other applications (I have not tested it though).

I do not have the time to implement this as it will need a lot of modification to the current code.

You (or whoever reads this in the future) are more than welcome to create a pull request and I will be more than happy to implement this into the project.

**Comment by jsericksk** [comment]
Any update on this? Do you plan to add this functionality in the future? @HBiSoft

**Comment by developwithrk** [comment]
> I will pin this issue for other users to see in the future. This question has been asked a couple of times.
> 
> As the library is now, it is not possible. You can have a look at the [AudioPlaybackCapture API](https://developer.android.com/guide/topics/media/av-capture#capture_audio_playback). Apparently, using this API, you will be able to retrieve/record audio from other applications (internal audio). I have not tested it though.
> 
> I do not have the time to implement this as it will need a lot of modification to the current code.
> 
> You (or whoever reads this in the future) are more than welcome to create a pull request and I will be more than happy to implement this into the project.

Please add Internal Audio Feature, even I see there have many filling issues to option. when recording all currently selected items was goes to default.

**Comment by Tamarindtype** [comment]
I need the internal audio aaaa, this app is so good for recording CODM at 60fps on my Helio G95 device😭

**Comment by anbarasu-seven** [comment]
I want this feature toooooo....
