### ISSUE TITLE
Exclude UI elements from Screen Recording

### ISSUE THREAD

**Issue by ShizaS** [HBiSoft/HBRecorder#98]
**Question** 
While capturing the screen with HBRecorder, is there a way to exclude UI elements from the recording?
 **Use Case**
 I'm developing an app that has a dual-camera feature. In the case of video capturing, I'm recording the screen. Now I have a capture button that I want to be displayed on the screen all the time, but I don't want it to be captured in screen recording so that the resultant video doesn't show that button. 
**Example**
Like in ios when capturing the screen with REPLAYKIT, we can hide certain UI elements by adding them in the secondary window since the kit only records the main window.

**Comment by HBiSoft** [comment]
I have not tested it but according to [this](https://stackoverflow.com/a/35997610/5550161) answer, you will be able to hide a view by making use of a `SurfaceView` and setting the secure flag to true. [Here](https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/MultiSurfaceActivity.java) is the example mentioned in that answer.

**Comment by ShizaS** [comment]
@HBiSoft as far as I understand setting the secure flag prevents taking screenshots of that screen. What I want is to allow the screen recording but don't show buttons in resultant video

**Comment by ShizaS** [comment]
@HBiSoft thanks for the tip. I tried this solution and it works. But the issue is the resultant video shows black part where the surface view is placed.
