### ISSUE TITLE
I am getting error whenever I try to open recorded video. I use this library to record screen overlays with open camera facing towards back.

### ISSUE THREAD

**Issue by AkmalAfzal07** [HBiSoft/HBRecorder#99]
READ THIS BEFORE OPENING AN ISSUE:
-----------------------
- Fill in all the information below.
- Have a look at previously asked questions to see if your issue has been resolved.
- Properly format your issue.
- All issues should be asked in English.
- Delete all the above before posting your issue

**Comment by HBiSoft** [comment]
Please see [Always fill in the issue template](https://github.com/HBiSoft/HBRecorder/issues/31)
